version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_SHA:-latest}
  build:
    commands:
      - echo "Build started on `date`"
      - docker build -t $IMAGE_REPOSITORY:$IMAGE_TAG .
      - docker tag $IMAGE_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY:$IMAGE_TAG
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Push the docker image to AWS ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY:$IMAGE_TAG
      - echo "Update IMAGE_TAG in docker-compose.yml..."
      - sed -i -e "s/\${IMAGE_TAG:-latest}/$IMAGE_TAG/g" docker-compose.yml
artifacts:
  files:
    - .ebextensions/**/*
    - docker-compose.yml
    - nginx.conf
cache:
  paths:
    - node_modules