version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: outfit-backend
    env_file:
      - ./backend/backend.env    # create this locally; do NOT commit
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: "http://localhost:8000"  # adjust for your env
    container_name: outfit-frontend
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_BASE: "http://localhost:8000"   # also available at runtime
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped