version: 0.2

env:
  variables:
    ECR_REPO_NAME: my-outfit-backend

phases:
  pre_build:
    commands:
      - set -e
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_REGION:-us-east-1}
      - |
        if [ -z "$ACCOUNT_ID" ] || [ "$ACCOUNT_ID" = "None" ]; then
          echo "ERROR: Could not resolve AWS account id"; exit 1; fi
      - ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
      - ECR_REPO_URI="${ECR_REGISTRY}/${ECR_REPO_NAME}"
      - echo "Logging in to ECR: $ECR_REGISTRY"
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"

  build:
    commands:
      - set -e
      - IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"
      - IMAGE_URI="${ECR_REPO_URI}:${IMAGE_TAG}"
      - echo "Building $IMAGE_URI"
      - docker build -t "$IMAGE_URI" -f backend/Dockerfile backend

  post_build:
    commands:
      - set -e
      - echo "Pushing $IMAGE_URI"
      - docker push "$IMAGE_URI"
      - printf '[{"name":"backend","imageUri":"%s"}]\n' "$IMAGE_URI" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes